#### dev开发环境配置

#server相关配置
server:
  port: 8081

spring:
  #mysql数据库,jpa,druid配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_slife?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        initial-size: 1                           # 初始化大小，最小，最大
        min-idle: 1
        max-active: 20
        max-wait: 60000                           # 配置获取连接等待超时的时间
        time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        min-evictable-idle-time-millis: 300000    # 配置一个连接在池中最小生存的时间，单位是毫秒
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #指定默认mysql引擎为InnoDB
  #文件上传配置(防止在接收文件时大小受限制)
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB
#配置日志级别
logging:
  level:
    root: info

#配置一些常量信息
common:
  slife:
    #QQ验证用户信息的官方接口api, openid, access_token为前端用户传入, oauth_consumer_key即为QQ开放平台申请的appId,
    #参考QQ官方文档: http://wiki.connect.qq.com/get_user_info
    qqVerifyUrl: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}
    qqAppId: 123456 #QQ开放平台申请的appId,用于验证获取用户信息权限

    #静态资源文件在本地的命令空间
    fileSpace: C:/Users/Z2/Desktop/slife-file

